### ISSUE TITLE
this doesnt work

### ISSUE THREAD

**Issue by codenoid** [MMcintire96/python_TinderAPI#4]
after sms verification i got this response

```
{'meta': {'status': 200}, 'data': {'refresh_token': 'xx', 'onboarding_token': 'xx', 'is_new_user': True}}
```

then i put `onboarding_token` on utils/config.py

then i ran example.py, i got this error 

```
[python_TinderAPI] $ python3 example.py 
Traceback (most recent call last):
  File "example.py", line 4, in <module>
    sess = tinder_api.session.Session() # inits the session
  File "/home/xxx/Programs/python_TinderAPI/tinder_api/session.py", line 10, in __init__
    self.auth = self.auth()
  File "/home/xxx/Programs/python_TinderAPI/tinder_api/session.py", line 19, in auth
    req = r.post('/auth/login/accountkit', {'token': c.tinder_token, 'id': c.tinder_token, 'client_version': '9.0.1'})
  File "/home/xxx/Programs/python_TinderAPI/tinder_api/utils/request_handlers.py", line 17, in post
    return r.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by rossheat** [comment]
Same error. Does anyone know if this repo is still being updated?

**Comment by codenoid** [comment]
nevermind, i already found new way, and it's pretty stable
